import { ACTIONS as ERROR_ACTIONS } from '../error/actionTypes';

export const ACTIONS = {
    SET_BOXES: 'set:boxes',

    FAILED_TO_FETCH_BOXES: ERROR_ACTIONS.SET_ERROR,
    FAILED_TO_BIND_BOX: ERROR_ACTIONS.SET_ERROR,
    FAILED_TO_PERFORM_BOXES_ACTION: ERROR_ACTIONS.SET_UNKNOWN_ERROR,
};
