version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - 5555:5432
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: cloud-box
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_box

  api:
    build: backend
    volumes:
      - ./backend:/var/www/apps/backend
    depends_on:
      - db

  nginx:
    build: nginx
    volumes:
      - ./frontend:/var/www/apps/frontend
    ports:
      - 8000:80
    depends_on:
      - api
