import { ACTIONS as ERROR_ACTIONS } from '../error/actionTypes';

export const ACTIONS = {
    FAILED_TO_REGISTER_USER: ERROR_ACTIONS.SET_ERROR,
    FAILED_TO_PERFORM_REGISTER_ACTION: ERROR_ACTIONS.SET_UNKNOWN_ERROR,
};
